spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        min-idle: 2
    timeout: 3000
  cache:
    type: redis